namespace CsharpKioskDemoDotnet.Shared.Logger;

public enum LogCode
{
    INVOICE_GET,
    INVOICE_GRID_GET,
    INVOICE_CREATE_SUCCESS,
    INVOICE_CREATE_FAIL,
    INVOICE_UPDATE_SUCCESS,
    INVOICE_UPDATE_FAIL,
    IPN_RECEIVED,
    IPN_VALIDATE_SUCCESS,
    IPN_VALIDATE_FAIL
}